### ISSUE TITLE
Failed to resolve: com.huawei.android.hms:push:2.5.2.300

### ISSUE THREAD

**Issue by YimasoftLiuGuanJun** [MEIZUPUSH/UpsDemo#6]
华为的依赖出现的错误。。。

**Comment by comsince** [comment]
什么错误

**Comment by jack921** [comment]
> 什么错误

Could not determine the dependencies of task ':app:prepareDebugDependencies'.
> Could not resolve all task dependencies for configuration ':app:_debugApk'.
   > Could not resolve com.huawei.android.hms:push:2.5.2.300.
     Required by:
         project :app > com.meizu.flyme.internet:push-ups:4.0.0
      > Could not resolve com.huawei.android.hms:push:2.5.2.300.
         > Could not get resource 'http://artifactory.rnd.meizu.com/artifactory/all/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom'.
            > Could not HEAD 'http://artifactory.rnd.meizu.com/artifactory/all/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom'. Received status code 502 from server: Server dropped connection
   > Could not resolve com.google.android.gms:play-services-measurement-api:[16.0.4].
     Required by:
         project :app > com.google.firebase:firebase-core:16.0.6 > com.google.firebase:firebase-analytics:16.0.6
         project :app > com.google.firebase:firebase-core:16.0.6 > com.google.firebase:firebase-measurement-connector-impl:17.0.4
      > Skipped due to earlier error
      > Failed to list versions for com.google.android.gms:play-services-measurement-api.
         > Unable to load Maven meta-data from http://artifactory.rnd.meizu.com/artifactory/libs-debug-local/com/google/android/gms/play-services-measurement-api/maven-metadata.xml.
            > Could not get resource 'http://artifactory.rnd.meizu.com/artifactory/libs-debug-local/com/google/android/gms/play-services-measurement-api/maven-metadata.xml'.
               > Could not GET 'http://artifactory.rnd.meizu.com/artifactory/libs-debug-local/com/google/android/gms/play-services-measurement-api/maven-metadata.xml'. Received status code 502 from server: Server dropped connection

**Comment by YimasoftLiuGuanJun** [comment]
emmm.....和楼上应该一样，你这个库依赖的华为push下载不了。
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.huawei.android.hms:push:2.5.2.300.
Searched in the following locations:
    file:/G:/allofmyprogram/android-sdk-windows/extras/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
    file:/G:/allofmyprogram/android-sdk-windows/extras/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
    file:/G:/allofmyprogram/android-sdk-windows/extras/google/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
    file:/G:/allofmyprogram/android-sdk-windows/extras/google/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
    file:/G:/allofmyprogram/android-sdk-windows/extras/android/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
    file:/G:/allofmyprogram/android-sdk-windows/extras/android/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
    https://dl.google.com/dl/android/maven2/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
    https://dl.google.com/dl/android/maven2/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
    https://jcenter.bintray.com/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
    https://jcenter.bintray.com/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
Required by:
    project :app > com.meizu.flyme.internet:push-ups:4.0.0
        at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:38)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:108)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:63)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:93)
        at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:60)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.resolve(ComponentState.java:163)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.getMetaData(ComponentState.java:174)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.calculateTargetConfigurations(EdgeState.java:137)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.attachToTargetConfigurations(EdgeState.java:108)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.attachToTargetRevisionsSerially(DependencyGraphBuilder.java:236)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:226)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:140)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:111)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:92)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:146)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:73)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$4.run(DefaultConfiguration.java:494)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:485)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:470)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:120)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:927)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:915)
        ... 40 more

**Comment by jack921** [comment]
> emmm.....和楼上应该一样，你这个库依赖的华为push下载不了。
> Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.huawei.android.hms:push:2.5.2.300.
> Searched in the following locations:
> file:/G:/allofmyprogram/android-sdk-windows/extras/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
> file:/G:/allofmyprogram/android-sdk-windows/extras/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
> file:/G:/allofmyprogram/android-sdk-windows/extras/google/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
> file:/G:/allofmyprogram/android-sdk-windows/extras/google/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
> file:/G:/allofmyprogram/android-sdk-windows/extras/android/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
> file:/G:/allofmyprogram/android-sdk-windows/extras/android/m2repository/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
> https://dl.google.com/dl/android/maven2/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
> https://dl.google.com/dl/android/maven2/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
> https://jcenter.bintray.com/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
> https://jcenter.bintray.com/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
> Required by:
> project :app > com.meizu.flyme.internet:push-ups:4.0.0
> at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:38)
> at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:108)
> at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:63)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:93)
> at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:60)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.resolve(ComponentState.java:163)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.getMetaData(ComponentState.java:174)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.calculateTargetConfigurations(EdgeState.java:137)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.attachToTargetConfigurations(EdgeState.java:108)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.attachToTargetRevisionsSerially(DependencyGraphBuilder.java:236)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:226)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:140)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:111)
> at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:92)
> at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:146)
> at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:73)
> at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
> at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$4.run(DefaultConfiguration.java:494)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
> at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
> at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:485)
> at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:470)
> at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:120)
> at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:927)
> at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:915)
> ... 40 more
怎么解决

**Comment by YimasoftLiuGuanJun** [comment]
应该是华为远程仓库已经移除了这个版本的华为push，所以下载不下来。  最新的HMS版本是2.6.3.30  。
得自己去下载这个2.5.2.300版本然后放在lib目录下？

**Comment by comsince** [comment]
https://github.com/MEIZUPUSH/UpsDemo/blob/master/build.gradle 参考下这个repo配置，你们应该是没有配置华为的仓库地址

**Comment by comsince** [comment]
https://github.com/MEIZUPUSH/UpsDemo/blob/master/QuickStart.md#%E4%B8%AD%E5%A4%AE%E4%BB%93%E5%BA%93%E8%87%AA%E5%8A%A8%E9%9B%86%E6%88%90
这里也有说明

**Comment by YimasoftLiuGuanJun** [comment]
就是那样配置的。
下面是报错的链接。你点击去就是404，说找不到资源。
https://jcenter.bintray.com/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.pom
https://jcenter.bintray.com/com/huawei/android/hms/push/2.5.2.300/push-2.5.2.300.jar
都返回
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}

**Comment by comsince** [comment]
华为的包是放在他们的私有仓库里面，不在
jcenter里面，你们可以到官网上看下是不是换了，版本号升级也可以，只要api兼容就行了

**Comment by jack921** [comment]
> 华为的包是放在他们的私有仓库里面，不在
> jcenter里面，你们可以到官网上看下是不是换了，版本号升级也可以，只要api兼容就行了

直接下载你们的aar里的库也可以吧

**Comment by YimasoftLiuGuanJun** [comment]
我看了下 他们私有的仓库的版本是 2.5.2.302

**Comment by comsince** [comment]
可以
